blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ General Questions
    url: https://github.com/starwaytrasporti/starwaytrasporti.com/discussions
    about: Ask questions and discuss ideas with the community

